services:
  - type: web
    name: gurbani-gpt
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && cd gurbani-gpt && npm install && npm run build && cd .."
    startCommand: "gunicorn --bind 0.0.0.0:$PORT server:app --timeout 180"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 20.10.0
